Update poetry to version 1.2.0
gaphor/gaphor pull request #1711
Opened 2022-09-05 13:31 UTC by danyeaw

This PR updates Poetry to version 1.2.0. In order to do that, it replaces the legacy way that poetry group dev and non-dev dependencies and creates new groups. An overview of this is in the [poetry 1.2.0 announcement](https://python-poetry.org/blog/announcing-poetry-1.2.0/)

### PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I have read, and I am following the [Contributor guide](https://github.com/gaphor/gaphor/blob/main/CONTRIBUTING.md)
- [X] I have read, and I understand the [Code of Conduct](https://github.com/gaphor/gaphor/blob/main/CODE_OF_CONDUCT.md)

### PR Type
What kind of change does this PR introduce?

- [ ] Bug fix
- [ ] Feature
- [X] Chore (refactoring, formatting, local variables, other cleanup)
- [ ] Documentation content changes

### What is the current behavior?

Issue Number: N/A

### What is the new behavior?

### Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### Other information

2022-09-05 20:34 UTC, amolenaar commented
The group functionality looks like a nice improvement over the current approach :+1:

2022-09-09 01:31 UTC, danyeaw commented
![image](https://user-images.githubusercontent.com/10014976/189253436-21a065a8-3f46-43eb-9f4e-85f16e1a3d53.png)
PyInstaller isn't packaging everything we need for some reason.

2022-09-09 19:55 UTC, amolenaar requested changes
I think this PR is mixing 2 things: updates for Poetry 1.2 and a new way to install stuff on Windows.

Is there a reason to combine these? I like the improvements for Poetry, since it removes a lot of "extras" from the distribution.

I'd rather not have the win32 `add_dll_directory` workaround.

2022-09-09 19:55 UTC, amolenaar commented on gaphor/ui/selftest.py
> +
There should be no need to put it here, if it's already defined in the `__init__.py` of the same module.

2022-09-09 19:55 UTC, amolenaar commented on gaphor/ui/__init__.py
> +    import gi
Why do we need this? Can't we use the old way instead?

2022-09-09 21:41 UTC, danyeaw commented
Unfortunately Poetry 1.2.0 will update installed packages even if I already have the correct version installed. So our previous method of installing the wheels from gvsbuild and then installing the other packages no longer works.

2022-09-11 11:19 UTC, amolenaar commented
The win32 patch can also be applied to 'gaphor/__init__.py', since Gaphas also requires this. Or a special module, similar to macos shim module.

2022-09-11 15:10 UTC, danyeaw commented
@amolenaar Ok, I refactored the logic and created a windowsshim module. Unfortunately, I can't get PyInstaller to work without https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/211 changes to PyGObject directly.

2022-09-12 06:56 UTC, amolenaar commented
This looks good. I think we do not need the same code in `selftest.py`. It's unfortunate we can't see why the windows self-test job is failing :disappointed: .

2022-09-12 14:58 UTC, amolenaar commented
Moving the windows fix up doesn't resolve the issue. It's like the import is already handled in the pyimod2- thingy 🤔

2022-09-12 16:03 UTC, amolenaar commented
I created 0948b674bcba1478c207ffc862b39fddd15cdb06 (branch poetry-1.2-test). This fixes the windows distribution.

Do we still need the workaround in our code then?

2022-09-13 00:16 UTC, danyeaw commented
Nice one @amolenaar, I didn't consider overriding the installed wheel after the poetry run.

pycairo doesn't need the workaround any longer, so we only need to override PyGObject, I updated the PR with just that one.

I think the workaround is still good, otherwise every time we run `poetry install` in Windows we need to then run `pip install --force-reinstall C:\gtk-build\build\x64\release\pygobject\*.whl` which is pretty annoying.

We should also squash and merge this one, somehow the git history got crazy ugly when rebasing - I must have run a git pull.

2022-09-13 09:05 UTC, amolenaar approved these changes

2022-09-13 10:27 UTC, merged

2022-09-13 10:27 UTC, amolenaar commented
> We should also squash and merge this one, somehow the git history got crazy ugly when rebasing - I must have run a git pull.

I fixed the git history and merged it. A nice improvement :+1:.