Update translation for docs.gaphor.org
gaphor/gaphor pull request #3663
Opened 2024-12-15 04:00 UTC by weblate

Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Gaphor/docs.gaphor.org](https://hosted.weblate.org/projects/gaphor/docs-gaphor-org/).

Current translation status:

![Weblate translation status](https://hosted.weblate.org/widget/gaphor/docs-gaphor-org/horizontal-auto.svg)

2024-12-15 12:33 UTC, amolenaar requested changes
In a couple of cases (there's also ones that are okay), the english CSS terms are translated.
If you would apply those to a style sheet, it will not work.

I suggest to use the english terms and add a translation in brackets.

I proposed a couple of changes, but there are more cases than the ones I addressed.

2024-12-15 12:33 UTC, amolenaar commented on docs/locale/fr/LC_MESSAGES/docs.po
> +"diagramme."
`color` and `font-family` are CSS keywords.

```suggestion
"Certaines propriétés sont héritées du style parent. Le parent est souvent un "
"diagramme. Lorsque vous définissez une `color` (couleur) ou une `font-family` "
"(famille de caractères) sur `diagram`, cela se propagera aux éléments contenus dans le "
"diagramme."
```

2024-12-15 12:33 UTC, amolenaar commented on docs/locale/fr/LC_MESSAGES/docs.po
> +msgstr "``couleur d'arrière-plan``"
`background-color` is a keyword. It should not be translated.

2024-12-15 12:33 UTC, amolenaar commented on docs/locale/fr/LC_MESSAGES/docs.po
> +msgstr "``couleur d'arrière-plan : azur ;``"
Same here.

```suggestion
msgstr "``background-color: azure;``"
```

2024-12-15 12:33 UTC, amolenaar commented on docs/locale/fr/LC_MESSAGES/docs.po
> +msgstr "``couleur d'arrière-plan : rgb(255, 255, 255) ;``"
Same here.

```suggestion
msgstr "``background-color: rgb(255, 255, 255);``"
```

etc.

2024-12-15 12:33 UTC, amolenaar commented on docs/locale/fr/LC_MESSAGES/docs.po
> +msgstr "``couleur d'arrière-plan : hsl(130, 95%, 10%) ;``"
```suggestion
msgstr "``background-color: hsl(130, 95%, 10%);``"
```

2024-12-15 12:33 UTC, amolenaar commented on docs/locale/fr/LC_MESSAGES/docs.po
> +msgstr "``couleur``"
```suggestion
msgstr "``color``"
```

2024-12-15 12:33 UTC, amolenaar commented on docs/locale/fr/LC_MESSAGES/docs.po
> +msgstr "``couleur-texte``"
```suggestion
msgstr "``text-color``"
```

2024-12-15 12:33 UTC, amolenaar commented on docs/locale/fr/LC_MESSAGES/docs.po
> +msgstr "``opacité``"
```suggestion
msgstr "``opacity``"
```

2024-12-15 12:33 UTC, amolenaar commented on docs/locale/fr/LC_MESSAGES/docs.po
> +msgstr "Soit ``normal`` ou ``italique``. *(hérité)*"
```suggestion
msgstr "Soit ``normal`` ou ``italic`` (italique). *(hérité)*"
```

2024-12-15 12:33 UTC, amolenaar commented on docs/locale/fr/LC_MESSAGES/docs.po
> +msgstr "Soit ``normal`` ou ``gras``. *(hérité)*"
```suggestion
msgstr "Soit ``normal`` ou ``bold`` (gras). *(hérité)*"
```

2024-12-15 12:33 UTC, amolenaar commented on docs/locale/fr/LC_MESSAGES/docs.po
> +msgstr "Soit ``gauche``, ``centre``, ``droite``. *(hérité)*"
```suggestion
msgstr "Soit ``left`` (gauche), ``center`` (centre), ``right`` (droite). *(hérité)*"
```

2024-12-15 12:33 UTC, amolenaar commented on docs/locale/fr/LC_MESSAGES/docs.po
> +msgstr "Soit ``non`` ou ``souligné``."
```suggestion
msgstr "Soit ``none`` (rien) ou ``underline`` (souligné)."
```

2024-12-15 12:33 UTC, amolenaar commented on docs/locale/fr/LC_MESSAGES/docs.po
> +msgstr "Soit ``haut``, ``milieu`` ou ``bas``."
```suggestion
msgstr "Soit ``top`` (haut), ``middle`` (milieu) or ``bottom`` (bas)."
```

2024-12-17 13:52 UTC, amolenaar commented
@stansz84 I think some keywords shouldn't have been translated (e.g. `background-color` from CSS). I added some suggestions in the comments.

2024-12-18 07:25 UTC, stansz84 commented
@amolenaar I've corrected all the words between the `quotes`.

2024-12-18 08:22 UTC, amolenaar approved these changes

2024-12-18 08:24 UTC, amolenaar commented
Thanks @stansz84. This is a lot better.

I also added the changes I already proposed.

2024-12-18 08:46 UTC, merged