Improve CSS text editor
gaphor/gaphor pull request #804
Opened 2021-05-14 12:51 UTC by vanillajonathan

This improves the CSS text editor to insert spaces instead of tabs, and to use 2-space indention and auto-indent.

2021-05-15 01:37 UTC, danyeaw requested changes
@vanillajonathan I am really excited to have you contribute this. Have you been able to get a development environment setup? We would be glad to answer any questions on Gitter as well. :+1: 

It looks like you are trying to apply the Gtk.Source.View methods to a Gtk.TextView and if you try to run Gaphor like this it throws an AttributeError. You might be on the right track that using the SourceView is what we want to improve the CSS editing experience. I couldn't find Gtk.Source.View in Glade though, so this may require some investigation on how to swap in the SourceView in to the `elementeditor.glade` file.

2021-05-15 01:37 UTC, danyeaw commented on gaphor/ui/elementeditor.py
> +        self.style_sheet_view.set_insert_spaces_instead_of_tabs(True)
`style_sheet_view` is a `Gtk.TextView` and the 3 indention methods you added are for the `Gtk.Source.View`.

2021-05-15 11:25 UTC, vanillajonathan commented
@danyeaw No, I haven't. I also used Gtk.Source so much that I thought those functions were available on Gtk.TextView too, but they're not.

Yeah, using Gtk.SourceView would be nice, because then you can get syntax highlighting, and auto indention, and insert tabs-as-spaces. The drawback is that it introduces a dependency.

I don't know how to declare GtkSourceView in Glade. It is not part of GTK, it is part of the gtksourceview library.

I found by searching: https://cjenkins.wordpress.com/2012/05/08/use-gtksourceview-widget-in-glade/
Which suggests:
```python
GObject.type_register(GtkSource.View)
```

2021-05-21 01:39 UTC, danyeaw commented
Hi @vanillajonathan, how is your development environment setup going?

2021-05-21 09:02 UTC, vanillajonathan commented
I haven't set it up, I just dropped by for a drive-by commit.

2021-05-22 18:20 UTC, danyeaw commented
Closing this. Glad to have you contribute if you decide to set up a dev environment. :+1:

2021-05-22 18:20 UTC, closed without merging